### PR TITLE
Resolve config rules directories

### LINKED ISSUE #65: Support custom rules
Atom seems to be throwing errors when using custom rules from https://www.npmjs.com/package/ng2lint in tslint.json.

### PR DESCRIPTION
**Pull request by arusakov**
Fix #65 I think.

@Arcanemagus @park9140 

This contains one breaking change. ```rulesDirectory``` from Atom package config has to be absolute path. It is much clearer and better than old resolving: 
```
directory = path.join textEditor.project.getPaths()[0], @rulesDirectory
```

### CODE REVIEW

**Comment by Arcanemagus** [comment]
`rulesDirectory` is coming from the `tslint.json`... does `tslint` expect it to be absolute? From the comments in #65 it sounds like it works perfectly fine with it being relative, which would mean this deviates from the behavior of `tslint` itself.

**Comment by arusakov** [comment]
@Arcanemagus thank you. I looked at https://github.com/palantir/tslint/blob/master/src/tslint-cli.ts#L201-L212 and it's very similar to this PR. So I get ```rulesDirectory``` resolution code from tslint-cli to the linter-tslint.

```rulesDirectory``` may come from tslint.json and also from linter-tslint settings. This is very similar to cli command ```tslint -r ./path``` but not enough. Because if ```rulesDirectory``` from linter-tslint settings is not absolute path, it's clear that it's relative path, but it's not clear relative to what it is.

**Comment by Arcanemagus** [comment]
Generally it's relative to the location of that configuration file, I'm not sure exactly how `tslint` behaves though.

**Comment by adammartin1981** [comment]
Cheers for your help - as an interim, I just copied the path of the tslint.json rulesDirectory into the global settings to linter-tslint Custom rules within Atom.

**Comment by arusakov** [comment]
@Arcanemagus 
```rulesDirectory``` from ```tslint.json``` is relative to the location of ```tslint.json```. But ```rulesDirectory``` from ```--rules-dir``` argument is relative to the current working directory. That is the problem. 
Our ```rulesDirectory``` from linter-tslint settings should be applied to any ```.ts``` file regardless of their locations. From this point of view our ```rulesDirectory``` setting from linter-tslint has to be absolute path.

**Comment by Arcanemagus** [comment]
As long as you are matching the behavior of `tslint` from the CLI merge away :wink:.

The whole idea is that when running a `linter-*` package the results seen within Atom should match what is seen from running the linter in the CLI, barring any overrides in the settings (which is what it seems like this does now).

**Pull request merged**
