### PR TITLE
Initial Adoption of Continous Deployment using semantic-release

### PR DESCRIPTION
**Pull request by keplersj**
To ease the modification/contribution to publish pipeline there has been some discussion of adopting a continuous deployment system for AtomLinter packages. To accomplish this we are making use of [`semantic-release`](https://github.com/semantic-release/semantic-release) and [`@semantic-release/apm-config`](https://github.com/semantic-release/apm-config).

This pull request has been [dynamically created using a script](https://gist.github.com/keplersj/8bc7622ea741c0964d12842bfc679c5d). While the result is not perfect, it does accompish most of the grunt work of adopting continous deployment. There is some reconciliation that needs to be done before this can be merged.

Among the things needed to be reconciled, an [APM Token](https://atom.io/account) and [GitHub Token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) will need to be added to this repo's continous integration (most likely [Travis CI](https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings)) configuration for automated deployments to work.

Again, this Pull Request has been created by a script made by @keplersj. Please mention him if something has gone wrong, and he'll be happy to help.

ref: AtomLinter/Meta#18

cc: @Arcanemagus

### CODE REVIEW

**Comment by Arcanemagus** [comment]
@AtomLinter/linter-tslint Any objections to the [Conventional Commits](https://conventionalcommits.org/) requirement? There _are_ alternative standards available if somebody has a strong objection to that standard, but we need to pick one to finish implementing this 😉.

**Comment by Xapphire13** [comment]
@arcanemagus, that convention looks good to me =].

@keplersj, will the tokens be checked in, in a public location? Or does the CI allow for secret storage? Haven't looked too much into the automatic deployment yet.

**Comment by Arcanemagus** [comment]
They can either be checked in encrypted in the file itself, or configured in the web interface for Travis CI. I'll go ahead and add those now 😉.

Note that this PR is **not** complete, check out https://github.com/AtomLinter/linter-jshint/pull/582 for an example on completing this. I can take care of it if you want, if you want to do it though just assign yourself the PR 😉.

**Pull request merged**
